# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed79ff31f42f71c482548c6e9da1d56e44c7b4e2ab64295cefffd178faaced8826337c51d2ca7e405f4cb519f4cc29df4ee9f7d89c406fa3ccd6d8cdd4e0a5dd

test:
  secret_key_base: 87d8287c3020217358c67ae312adff72af5042ba5bc8e6a0cdce875205befd865e4f891a21894b4bf9ae310e77fe1c04574daf72affbd67688ef4634f0bf953b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
